### ISSUE TITLE
CONTRIBUTING FILE 

### ISSUE THREAD

**Issue by akrish4** [djm-1/quizmaster-reloaded#3]
Hi @djm-1 
I would like to contribute to this amazing project
I would like to add a `CONTRIBUTING.md` file which will contain all contributing guidelines and all git workflow so that all newbies or beginers and even experts can look into into it and also the contributors will understand the workflow

Kindly do assign me

Kindly add the labels also

**Comment by djm-1** [comment]
Go for it 👍

**Comment by akrish4** [comment]
thank you
