### ISSUE TITLE
CODE OF CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [djm-1/quizmaster-reloaded#4]
Hi @djm-1 

There is no code of conduct file in this repository
code of conduct is a file that will be required to a open source project for the contributors to follow the decorum
Kindly let me know if you can assign me this issue

**Comment by djm-1** [comment]
Keep going!!!

**Comment by akrish4** [comment]
Hi @djm-1 
thank you for assigning me 
Kindly pls do add DWOC and Level label

**Comment by djm-1** [comment]
Yes👍
