### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [djm-1/quizmaster-reloaded#6]
Like this
![image](https://user-images.githubusercontent.com/68433936/104821264-a26ba380-5860-11eb-9d20-339027311da6.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by djm-1** [comment]
Looks great...Ok, keep going.

**Comment by djm-1** [comment]
Ok, it's merged. Keep coding !!!
